// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjngmyxnrockbwefzyaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbmdteXhucm9ja2J3ZWZ6eWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTAyMzUsImV4cCI6MjA2ODY4NjIzNX0.Pic6CGc-J4rWpSY6oZXG1D0XGrfrBB8Dk2mdCM7XvO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});